#!/bin/bash -x

# REQUIREMENTS: 
# - sake installed as executable
# - _ss_environments.php file in place.
# - git client
# - piston rubygem
# - superuser access

# TODO: Check that the root directory is empty besides the .git folder

ssv='master'
database=
dbu='root'
dbp=''
template=


if [ $(id -u) = "0" ]; 
then
	# Parse 
	while [ "$1" != "" ]; do
	    case $1 in
	        -t | --template )          shift
	                                	template=$1
	                                	;;
			-ssv | --version )          shift
	                                	ssv=$1
										echo "Installing SilverStripe version "$ssv
	                                	;;
			-db | --database )          shift
	                                	database=$1
										echo $database
	                                	;;
	        -dbu | --databaseuser )    	shift
										dbu=$1
										echo $dbu
	                                	;;
			-dbp | --databasepass )     shift
										dbp=$1
										echo $dbp
										;;
			-h | --help )           	usage
										exit
										;;
	        * )                     	usage
	                                	exit 1
	    esac
	    shift
	done
	
	# Make sure a database has been indicated
	if [ "$database" = "" ]; then
		echo "No database selected.  Please use -db [database_name]."
		exit 1
	fi
	
	if [ "$template" = "" ]; then
		echo "No piston template file selected.  Please use -t [template_file]."
		exit 1
	fi
	
	# Download and extract latest release
	sszip="ss"$ssv".zip"
	ssurl="https://github.com/silverstripe/silverstripe-installer/zipball/"$ssv
	echo $ssurl
	curl -L -o $sszip $ssurl
	tar -vxf $sszip
	rm -R $sszip
	
	# Move the extracted files into our root
	mv silverstripe-silverstripe-installer*/* ./
	mv silverstripe-silverstripe-installer*/.* ./
	rm -R silverstripe-silverstripe-installer*
	
	# Use piston to get the newest version of the core modules (sapphire, cms) and extension
	# modules indicated in the template file.
	tools/new-project -t "$template"
	
	# Add local cache folder
	mkdir silverstripe-cache
	sudo chmod -R 777 silverstripe-cache
	
	# Add the .htaccess file, and set all necessary file permissions
	# TODO
	chmod 777 .htaccess
	chmod -R 777 assets
	chmod 777 mysite/_config.php
	
	# Ignore the cache and assets folders
	touch .gitignore
	echo ".DS_Store
		silverstripe-cache
		assets
	" > .gitignore
	
	# Add database to the mysite _config.php file
	search_string="\$database = '';"
	replace_string="\$database = '$database';"
	sed -i '' "s/$search_string/$replace_string/g" mysite/_config.php
	
	# Switch to the default html5 boilerplate theme
	sed -i '' 's/blackcandy/html5/g' mysite/_config.php
	
	# Add the base URL to the .htaccess file
	# TODO: Add HTML5 Boilerplate base .htaccess rules
	$search_string="RewriteEngine On"
	$replace_string="RewriteEngine On
	RewriteBase /
	"
	sed -i '' "s/$search_string/$replace_string/g" .htaccess
	
	# Add to git repo and do an initial commit
	git add *
	sudo git commit -am "initial commit"
	
	# Build the database!
	sake dev/build
	
	exit 0
else
	echo "You do not have permission to run sssetup."
	exit 1
fi